CREATE TABLE UserInfo (
	UserName VARCHAR(15) NOT NULL,
	PRIMARY KEY(UserName));

CREATE TABLE GameLobbyInfo (
	GameID VARCHAR(45) NOT NULL,
	P1 VARCHAR(15) NULL,
	P2 VARCHAR(15) NULL,
	P3 VARCHAR(15) NULL,
	P4 VARCHAR(15) NULL,
	PRIMARY KEY (GameID));
	
CREATE TABLE GameBoardInfo (
	GameID VARCHAR(45) NOT NULL, 
	MoveRecord VARCHAR(5000) NULL,
	PRIMARY KEY (GameID));

